version: '3.6'

services:
  postgres:
    image: postgres:10.4-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - c:/opt/db1:/var/lib/postgresql/data